### ISSUE TITLE
Not an issue. Humble request for adding support for CheckMK 2.3

### ISSUE THREAD

**Issue by danielbgto** [jiuka/checkmk_crl_url#3]
Hi! Your plugings are wonderful!!
CheckMK just released today (06-03-2024) version 2.3b1 and your CRL plugin is not compatible with it. It's still beta but I guess the final release is month or two ahead. 

Thank you! 

![image](https://github.com/jiuka/checkmk_crl_url/assets/5525957/8509f224-ae30-4b35-a607-056a11c1a4c5)

**Comment by jiuka** [comment]
Hi @danielbgto 

I tried to upgrade it to there new api. However I was not able to test it yet.

https://github.com/jiuka/checkmk_crl_url/actions/runs/8203121899

But as far as I can tell there is a bug in in the 2.3.0b1 which prevents it from finding the active check executables.

 - Marius

**Comment by jiuka** [comment]
The new release [v2.3.0](https://github.com/jiuka/checkmk_crl_url/releases/tag/v2.3.0) is ready
